name: learn_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_messaging: ^11.2.8
  flutter_local_notifications: ^9.4.0
  firebase_core: ^1.13.1
  google_maps_flutter: ^2.1.2
  geolocator: ^8.2.0
  get: ^4.6.1
  intl: ^0.17.0
  geocoding: ^2.0.4
  http: ^0.13.4
  flutter_typeahead: ^3.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


